#!/bin/sh

### BEGIN INIT INFO
# Provides:        curl
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start curl facebook
### END INIT INFO

start() {
	sh /home/pi/Desktop/demo/curl.sh &
        echo
}

stop() {
	ps aux|grep curl | awk '{print $2}' | xargs -n1 sudo kill $1
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status mirai
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
